# SecureAI DeepFake Detection System
# Regulatory Compliance Configuration

# Compliance frameworks and requirements
compliance_frameworks:
  gdpr:
    name: "General Data Protection Regulation (EU)"
    jurisdiction: "European Union"
    effective_date: "2018-05-25"
    authority: "Data Protection Authorities"
    penalties:
      max_fine: "€20M or 4% of annual revenue"
      typical_fine: "€50,000 - €500,000"
    
    requirements:
      - id: "GDPR-001"
        title: "Data Processing Lawful Basis"
        category: "Legal Basis"
        mandatory: true
        risk_level: "high"
        description: "Establish and document lawful basis for data processing"
        implementation_status: "implemented"
        evidence_required:
          - "DPIA document"
          - "Processing agreements"
          - "Legal basis documentation"
        assessment_criteria:
          - "Lawful basis identified and documented"
          - "Balancing test completed"
          - "Regular review of lawful basis"
      
      - id: "GDPR-002"
        title: "Data Subject Rights"
        category: "Data Subject Rights"
        mandatory: true
        risk_level: "high"
        description: "Implement data subject rights (access, rectification, erasure, portability)"
        implementation_status: "implemented"
        evidence_required:
          - "API endpoints for data subject requests"
          - "User dashboard for data management"
          - "Request handling procedures"
          - "Response time tracking"
        assessment_criteria:
          - "All data subject rights implemented"
          - "Response times within 30 days"
          - "Identity verification procedures"
          - "Request tracking and logging"
      
      - id: "GDPR-003"
        title: "Data Protection by Design"
        category: "Technical Measures"
        mandatory: true
        risk_level: "medium"
        description: "Implement privacy by design and by default"
        implementation_status: "implemented"
        evidence_required:
          - "System architecture documentation"
          - "Data minimization implementation"
          - "Encryption implementation"
          - "Access control documentation"
        assessment_criteria:
          - "Privacy considerations in system design"
          - "Data minimization implemented"
          - "Default privacy settings"
          - "Technical safeguards in place"
      
      - id: "GDPR-004"
        title: "Data Protection Impact Assessment"
        category: "Risk Assessment"
        mandatory: true
        risk_level: "high"
        description: "Conduct and maintain DPIA for high-risk processing"
        implementation_status: "implemented"
        evidence_required:
          - "DPIA document"
          - "Risk assessment methodology"
          - "Mitigation measures documentation"
          - "Review and update procedures"
        assessment_criteria:
          - "DPIA conducted for high-risk processing"
          - "Risks identified and assessed"
          - "Mitigation measures implemented"
          - "Regular review and updates"
      
      - id: "GDPR-005"
        title: "Data Breach Notification"
        category: "Incident Management"
        mandatory: true
        risk_level: "high"
        description: "Implement data breach notification procedures"
        implementation_status: "implemented"
        evidence_required:
          - "Breach detection procedures"
          - "Notification procedures"
          - "Documentation requirements"
          - "Training materials"
        assessment_criteria:
          - "Breach detection mechanisms"
          - "72-hour notification capability"
          - "Documentation procedures"
          - "Staff training on breach procedures"

  ccpa:
    name: "California Consumer Privacy Act"
    jurisdiction: "California, USA"
    effective_date: "2020-01-01"
    authority: "California Attorney General"
    penalties:
      max_fine: "$7,500 per violation"
      typical_fine: "$2,500 - $7,500"
    
    requirements:
      - id: "CCPA-001"
        title: "Consumer Rights Implementation"
        category: "Consumer Rights"
        mandatory: true
        risk_level: "medium"
        description: "Implement consumer rights (know, delete, opt-out, correct)"
        implementation_status: "implemented"
        evidence_required:
          - "Privacy policy with consumer rights"
          - "Consumer request procedures"
          - "API endpoints for consumer requests"
          - "Verification procedures"
        assessment_criteria:
          - "All consumer rights implemented"
          - "45-day response time"
          - "Identity verification"
          - "Request tracking and logging"
      
      - id: "CCPA-002"
        title: "Data Categories Disclosure"
        category: "Transparency"
        mandatory: true
        risk_level: "medium"
        description: "Disclose categories of personal information collected"
        implementation_status: "implemented"
        evidence_required:
          - "Privacy policy with data categories"
          - "Data inventory"
          - "Category mapping documentation"
          - "Regular updates to disclosures"
        assessment_criteria:
          - "All data categories disclosed"
          - "Clear and understandable language"
          - "Regular updates"
          - "Accessible format"
      
      - id: "CCPA-003"
        title: "Third-Party Sharing Controls"
        category: "Data Sharing"
        mandatory: true
        risk_level: "medium"
        description: "Implement controls for third-party data sharing"
        implementation_status: "implemented"
        evidence_required:
          - "Data sharing agreements"
          - "Opt-out mechanisms"
          - "Verification procedures"
          - "Sharing limitation controls"
        assessment_criteria:
          - "Third-party sharing disclosed"
          - "Opt-out mechanisms functional"
          - "Verification procedures in place"
          - "Sharing limitations implemented"

  ai_act:
    name: "European Union Artificial Intelligence Act"
    jurisdiction: "European Union"
    effective_date: "2024-12-01"
    authority: "European Commission"
    penalties:
      max_fine: "€30M or 6% of annual revenue"
      typical_fine: "€1M - €10M"
    
    requirements:
      - id: "AI-001"
        title: "Risk Management System"
        category: "Risk Management"
        mandatory: true
        risk_level: "high"
        description: "Implement AI risk management system"
        implementation_status: "implemented"
        evidence_required:
          - "Risk assessment methodology"
          - "Risk mitigation measures"
          - "Monitoring procedures"
          - "Incident response procedures"
        assessment_criteria:
          - "Comprehensive risk assessment"
          - "Risk mitigation measures"
          - "Continuous monitoring"
          - "Incident response procedures"
      
      - id: "AI-002"
        title: "Data Governance"
        category: "Data Governance"
        mandatory: true
        risk_level: "medium"
        description: "Implement data governance for AI systems"
        implementation_status: "implemented"
        evidence_required:
          - "Data quality procedures"
          - "Data protection measures"
          - "Data retention policies"
          - "Data minimization practices"
        assessment_criteria:
          - "Data quality management"
          - "Data protection measures"
          - "Appropriate data retention"
          - "Data minimization implemented"
      
      - id: "AI-003"
        title: "Technical Documentation"
        category: "Documentation"
        mandatory: true
        risk_level: "medium"
        description: "Maintain comprehensive technical documentation"
        implementation_status: "implemented"
        evidence_required:
          - "System architecture documentation"
          - "Algorithm documentation"
          - "Performance metrics"
          - "Testing procedures"
        assessment_criteria:
          - "Comprehensive system documentation"
          - "Algorithm transparency"
          - "Performance metrics available"
          - "Testing procedures documented"
      
      - id: "AI-004"
        title: "Human Oversight"
        category: "Human Oversight"
        mandatory: true
        risk_level: "medium"
        description: "Implement human oversight mechanisms"
        implementation_status: "implemented"
        evidence_required:
          - "Oversight procedures"
          - "Human review process"
          - "Escalation mechanisms"
          - "Decision authority documentation"
        assessment_criteria:
          - "Human oversight procedures"
          - "Review process for decisions"
          - "Escalation mechanisms"
          - "Clear decision authority"
      
      - id: "AI-005"
        title: "Accuracy and Robustness"
        category: "Technical Requirements"
        mandatory: true
        risk_level: "high"
        description: "Ensure AI system accuracy and robustness"
        implementation_status: "implemented"
        evidence_required:
          - "Performance testing results"
          - "Accuracy metrics"
          - "Robustness testing"
          - "Quality assurance procedures"
        assessment_criteria:
          - "Performance meets requirements"
          - "Accuracy metrics documented"
          - "Robustness testing conducted"
          - "Quality assurance in place"

# Assessment configuration
assessment_config:
  default_frameworks:
    - "gdpr"
    - "ccpa"
    - "ai_act"
  
  assessment_frequency:
    gdpr: "quarterly"
    ccpa: "quarterly"
    ai_act: "quarterly"
    comprehensive: "annually"
  
  risk_thresholds:
    low: 0.8
    medium: 0.6
    high: 0.4
    critical: 0.2
  
  scoring_weights:
    mandatory_requirements: 3.0
    high_risk_requirements: 2.0
    medium_risk_requirements: 1.5
    low_risk_requirements: 1.0

# Reporting configuration
reporting_config:
  report_formats:
    - "json"
    - "yaml"
    - "html"
    - "pdf"
  
  report_sections:
    - "executive_summary"
    - "framework_results"
    - "detailed_findings"
    - "recommendations"
    - "remediation_plan"
    - "next_steps"
  
  stakeholders:
    - "executive_team"
    - "compliance_team"
    - "legal_team"
    - "security_team"
    - "data_protection_officer"
  
  notification_settings:
    on_assessment_completion: true
    on_high_risk_findings: true
    on_critical_findings: true
    notification_channels:
      - "email"
      - "slack"
      - "teams"

# Evidence management
evidence_management:
  evidence_types:
    - "documents"
    - "screenshots"
    - "configuration_files"
    - "test_results"
    - "audit_logs"
    - "training_materials"
  
  storage_requirements:
    retention_period: "7_years"
    encryption_required: true
    access_controls: "role_based"
    backup_frequency: "daily"
  
  evidence_categories:
    technical:
      - "system_architecture"
      - "configuration_files"
      - "test_results"
      - "performance_metrics"
    
    procedural:
      - "policies"
      - "procedures"
      - "training_materials"
      - "audit_reports"
    
    legal:
      - "contracts"
      - "agreements"
      - "legal_opinions"
      - "regulatory_guidance"

# Remediation management
remediation_config:
  remediation_priorities:
    critical: "immediate"
    high: "30_days"
    medium: "90_days"
    low: "180_days"
  
  remediation_categories:
    - "technical_implementation"
    - "policy_development"
    - "training_development"
    - "process_improvement"
    - "documentation_updates"
  
  approval_workflow:
    low_priority: "compliance_manager"
    medium_priority: "compliance_director"
    high_priority: "chief_compliance_officer"
    critical_priority: "executive_team"
  
  tracking_requirements:
    - "remediation_plan"
    - "target_completion_date"
    - "assigned_resources"
    - "progress_updates"
    - "completion_verification"

# Monitoring and alerting
monitoring_config:
  continuous_monitoring:
    enabled: true
    frequency: "daily"
    automated_checks:
      - "data_subject_request_response_times"
      - "breach_detection_systems"
      - "access_control_violations"
      - "data_retention_compliance"
  
  alerting_thresholds:
    response_time_exceeded: "15_days"
    breach_detection: "immediate"
    access_violation: "immediate"
    retention_violation: "7_days"
  
  escalation_procedures:
    level_1: "compliance_team"
    level_2: "compliance_director"
    level_3: "chief_compliance_officer"
    level_4: "executive_team"

# Integration settings
integration_config:
  siem_integration:
    enabled: true
    platforms:
      - "splunk"
      - "qradar"
      - "arcsight"
  
  ticketing_system:
    enabled: true
    platforms:
      - "servicenow"
      - "jira"
      - "azure_devops"
  
  notification_systems:
    enabled: true
    platforms:
      - "slack"
      - "teams"
      - "email"
      - "pagerduty"

# Training and awareness
training_config:
  mandatory_training:
    - "gdpr_awareness"
    - "data_protection_basics"
    - "ai_ethics"
    - "incident_response"
  
  training_frequency:
    initial: "onboarding"
    refresher: "annually"
    updates: "as_needed"
  
  training_materials:
    - "online_modules"
    - "instructor_led"
    - "workshops"
    - "simulations"
  
  assessment_requirements:
    passing_score: 80
    retake_allowed: true
    certification_validity: "1_year"

# Audit and review
audit_config:
  internal_audits:
    frequency: "quarterly"
    scope: "full_compliance"
    auditors: "internal_compliance_team"
  
  external_audits:
    frequency: "annually"
    scope: "comprehensive"
    auditors: "certified_compliance_auditors"
  
  regulatory_reviews:
    frequency: "as_required"
    scope: "regulatory_specific"
    reviewers: "regulatory_experts"
  
  audit_evidence:
    - "compliance_assessments"
    - "remediation_plans"
    - "training_records"
    - "incident_reports"
    - "policy_updates"
